CXX = g++
CXXFLAGS = -g -Wall -Wextra -std=c++11
CXXOPENCV = -I/usr/local/include/opencv -I/usr/local/include/opencv2 -L/usr/local/lib/ -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_stitching

all: conv

conv: conv.cpp
	$(CXX) $(CXXFLAGS) $^ -o $@ $(CXXOPENCV)

.PHONY: all
